name: ApproveRules
version: 2021.11.15
author: The-Repo-Club
main: club.therepo.ApproveRules
api-version: 1.17
depend:
  - LuckPerms
commands:
  acceptrules:
    description: Accept the rules!
    aliases:
      - rulesaccept
    usage: /<command>
  rules:
    description: Read the rules!
    usage: /<command>
permissions:
  approverules.read:
    default: false
    description: Allows you be able to move and interact with the world.